# Generated by Django 4.1.5 on 2023-02-06 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 28, 21, 457200, tzinfo=datetime.timezone.utc)),
        ),
    ]
