# Generated by Django 4.1.5 on 2023-02-06 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0005_alter_rdv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 12, 57, 32, 215723, tzinfo=datetime.timezone.utc)),
        ),
    ]
