# Generated by Django 4.1.5 on 2023-02-06 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0006_alter_rdv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 54, 43, 256254, tzinfo=datetime.timezone.utc)),
        ),
    ]
