# Generated by Django 4.1.5 on 2023-02-07 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0007_rdv_user_alter_rdv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 13, 7, 43, 98854, tzinfo=datetime.timezone.utc)),
        ),
    ]
