# Generated by Django 4.1.5 on 2023-02-07 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0008_rdv_notes_alter_rdv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='CLIENT', max_length=6),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 15, 34, 8, 928809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='notes',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
