# Generated by Django 4.1.5 on 2023-02-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0009_user_role_alter_rdv_date_alter_rdv_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 8, 44, 22, 582588, tzinfo=datetime.timezone.utc)),
        ),
    ]
