# Generated by Django 4.1.5 on 2023-02-13 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0014_alter_rdv_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 10, 20, 6, 316866, tzinfo=datetime.timezone.utc)),
        ),
    ]
